[package]
name = "multi-eq-use-tests"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]
edition = "2018"

[dev-dependencies.multi-eq-derive-tests]
path = "../multi-eq-derive-tests"

[dev-dependencies.multi-eq]
path = ".."
